{
  "hash": "24f53e99173bcb7a853ce04e19e9f536",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Baseline+RF vs SIRUS\"\nsubtitle: \"Comparaison directe sur les mêmes runs : qui choisit le meilleur code, et qui offre le meilleur compromis volume automatisé / fiabilité ?\"\ndate: today\nengine: knitr\nformat:\n  html:\n    toc-depth: 2\n    df-print: kable\nexecute:\n  echo: false\n  warning: false\n  message: false\n---\n\nCette page compare directement les deux alternatives au LLM-as-a-judge\ndéveloppées pendant le stage — [la baseline (vote majoritaire) filtrée par\nune Random Forest](index.qmd) et [SIRUS](sirus.qmd) — sur les mêmes 3 runs\nlabellisés (`codif-vvkv9`, `codif-8m8jn`, `codif-x98xl`), calculées ici\nmême (pas des chiffres recopiés) pour que les deux résultats soient\nstrictement comparables.\n\n**Ce que les deux modèles ont en commun** : ils partent tous les deux des\nmêmes 4 classifieurs de base, et rendent tous les deux une probabilité de\nconfiance servant à décider si on peut coder automatiquement ou s'il faut\nescalader (reprise manuelle / LLM-judge).\n\n**Ce qui les distingue structurellement** : la baseline+RF ne choisit\njamais elle-même un code — la RF se contente de dire si on peut faire\nconfiance au vote majoritaire (déjà figé en amont). SIRUS, lui, **reclasse\nles candidats des 4 classifieurs** et peut donc choisir un candidat\ndifférent du vote majoritaire. C'est ce qui explique l'essentiel de l'écart\nobservé plus bas.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n## Précision du code proposé\n\nAccuracy du code effectivement proposé par chacune des deux approches, sur\n**le même test 20 %** (les deux modèles sont désormais évalués sur\nexactement les mêmes produits, cf. section suivante). Pour SIRUS, la \"borne\nhaute\" est le plafond atteignable si on choisissait toujours le meilleur\ncandidat disponible parmi les 4 classifieurs — elle n'existe pas pour la\nbaseline, qui ne choisit jamais qu'un seul code fixé en amont (le vote\nmajoritaire).\n\n\n::: {.cell}\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Modèle                      |Accuracy candidat-level |Accuracy produit-level |Borne haute |\n|:---------------------------|:-----------------------|:----------------------|:-----------|\n|Baseline (vote majoritaire) |—                       |78.4%                  |—           |\n|SIRUS                       |86.9%                   |84.1%                  |91.7%       |\n\n</div>\n:::\n:::\n\n\nSIRUS re-classe les candidats des 4 classifieurs plutôt que de suivre le\nvote majoritaire figé : c'est ce qui lui permet de dépasser l'accuracy de\nla baseline (78.4%), et d'approcher\nsa propre borne haute (91.7%).\nLa baseline+RF, elle, ne peut structurellement jamais dépasser\n78.4% : le RF ne change jamais le\ncode proposé, il ne fait qu'estimer si ce code fixe est fiable.\n\n## Significativité de l'écart (test de McNemar)\n\nL'écart mesuré ci-dessus porte sur 3508 produits de\ntest : est-il assez net pour ne pas être un simple effet d'échantillonnage ?\nLe [test de McNemar](https://fr.wikipedia.org/wiki/Test_de_McNemar) répond à\ncette question précise, en comparant les deux modèles **produit par\nproduit** (contrairement aux sections précédentes, qui ne faisaient que\ncomparer deux taux globaux) : il ne regarde que les cas où les deux modèles\nsont en désaccord, et teste si ce désaccord penche significativement du même\ncôté à chaque fois.\n\n\n::: {.cell}\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|SIRUS \\ Baseline | faux| correct|\n|:----------------|----:|-------:|\n|faux             |  469|      90|\n|correct          |  289|    2660|\n\n</div>\n:::\n:::\n\n\nSur les 3508 produits du test, les deux modèles\nsont en désaccord dans 379 cas : SIRUS seul a\nraison dans 289 cas, la baseline seule a raison dans\n90 cas. Le test de McNemar (avec correction de continuité)\ndonne :\n\n- statistique du test : 103.4\n  (1 degré de liberté)\n- p-value : <1e-04\n\n\n::: {.cell}\n\n:::\n\n\nLa p-value est très inférieure au seuil usuel de 5 % : l'avantage de SIRUS sur la baseline n'est pas un effet du hasard d'échantillonnage — il est statistiquement significatif, et concentré (comme attendu) dans le sens où SIRUS rattrape des cas que la baseline rate, beaucoup plus souvent que l'inverse.\n\n## Compromis volume automatisé / fiabilité\n\nPour chaque modèle, part du volume qu'on peut coder automatiquement (sans\nLLM ni reprise manuelle) à un seuil de confiance donné, et fiabilité\nobservée sur ce sous-ensemble.\n\n\n::: {.cell}\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Modèle      | Seuil|Volume auto-codé |Fiabilité |\n|:-----------|-----:|:----------------|:---------|\n|SIRUS       |   0.3|100.0%           |84.1%     |\n|SIRUS       |   0.4|96.5%            |86.6%     |\n|SIRUS       |   0.5|81.6%            |90.2%     |\n|SIRUS       |   0.6|66.4%            |96.1%     |\n|SIRUS       |   0.7|61.0%            |96.5%     |\n|Baseline+RF |   0.3|82.6%            |91.5%     |\n|Baseline+RF |   0.4|76.9%            |93.5%     |\n|Baseline+RF |   0.5|70.6%            |95.3%     |\n|Baseline+RF |   0.6|63.5%            |96.9%     |\n|Baseline+RF |   0.7|57.0%            |97.9%     |\n|Baseline+RF |   0.8|48.6%            |98.6%     |\n|Baseline+RF |   0.9|37.4%            |99.2%     |\n\n</div>\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nÀ seuil égal (0.6), les deux modèles donnent un volume et une fiabilité\nétonnamment proches. La différence structurelle apparaît aux seuils plus\nélevés : la RF explore toute la plage `[0, 1]` (ici observée entre\n0.00 et 1.00), et\npeut donc pousser la fiabilité au-delà de 99 % en sacrifiant du volume.\nSIRUS, avec seulement 10 règles de profondeur 2,\nreste cantonné à une plage de confiance beaucoup plus étroite (observée\nentre 0.36 et 0.74\nsur ces données) : au-delà de ~0.7, plus aucun candidat n'atteint ce niveau\nde confiance, le seuil devient inutilisable.\n\n## Ce que ça implique\n\n- **Pour la seule qualité du code proposé, SIRUS gagne, et l'écart est\n  statistiquement significatif** (test de McNemar, p < 0.001) : il choisit\n  activement le meilleur candidat plutôt que de suivre un vote figé.\n- **Pour le compromis volume/fiabilité à seuil modéré (~0.6), les deux se\n  valent** : environ deux tiers du volume automatisable à plus de 95 % de\n  fiabilité.\n- **La RF offre un réglage plus fin** aux seuils élevés (jusqu'à 99 %+ de\n  fiabilité en sacrifiant du volume), là où SIRUS plafonne structurellement.\n- **SIRUS reste le seul des deux lisible sous forme de règles auditables**\n  (cf. [Pourquoi SIRUS ?](sirus.qmd#pourquoi-sirus)) — la RF est une\n  boîte noire à ~300 arbres, seules ses importances de features sont\n  interprétables, pas une décision individuelle.\n\nCompte tenu de l'objectif du stage (réduire l'appel au LLM-judge **et**\npouvoir documenter/auditer la règle de décision), SIRUS reste la piste\nrecommandée pour la suite — la RF constitue une alternative de repli plus\nprécise mais moins transparente, utile si l'auditabilité n'est pas un\ncritère bloquant.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}