<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-08-21">

<title>Interprétation — run du 2026-06-29 – Codification automatique COICOP</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-505cb934e192d125575319552c8b77a8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Codification automatique COICOP</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Accueil</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../stats-descriptives/index.html"> 
<span class="menu-text">Fiabilité des classifieurs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../modelisation/index.html"> 
<span class="menu-text">Modélisation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../interpretation/index.html"> 
<span class="menu-text">Interprétation</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#analyse-des-erreurs-de-la-baseline" id="toc-analyse-des-erreurs-de-la-baseline" class="nav-link active" data-scroll-target="#analyse-des-erreurs-de-la-baseline">Analyse des erreurs de la baseline</a></li>
  <li><a href="#performance-du-modèle" id="toc-performance-du-modèle" class="nav-link" data-scroll-target="#performance-du-modèle">Performance du modèle</a></li>
  <li><a href="#erreurs-manquées-par-le-modèle" id="toc-erreurs-manquées-par-le-modèle" class="nav-link" data-scroll-target="#erreurs-manquées-par-le-modèle">Erreurs manquées par le modèle</a></li>
  <li><a href="#réannotation-manuelle-de-35-cas-manqués-par-la-rf" id="toc-réannotation-manuelle-de-35-cas-manqués-par-la-rf" class="nav-link" data-scroll-target="#réannotation-manuelle-de-35-cas-manqués-par-la-rf">Réannotation manuelle de 35 cas manqués par la RF</a></li>
  <li><a href="#compromis-précisionrappel" id="toc-compromis-précisionrappel" class="nav-link" data-scroll-target="#compromis-précisionrappel">Compromis précision/rappel</a></li>
  <li><a href="#modèle-de-re-ranking-sirus-diagnostic-de-la-baisse-daccuracy-sur-les-runs-suivants" id="toc-modèle-de-re-ranking-sirus-diagnostic-de-la-baisse-daccuracy-sur-les-runs-suivants" class="nav-link" data-scroll-target="#modèle-de-re-ranking-sirus-diagnostic-de-la-baisse-daccuracy-sur-les-runs-suivants">Modèle de re-ranking SIRUS : diagnostic de la baisse d’accuracy sur les runs suivants</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Interprétation — run du 2026-06-29</h1>
<p class="subtitle lead">codif-vvkv9 — notes figées, à mettre à jour manuellement pour un nouveau run</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 21, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Cette page documente la lecture des résultats du run <code>s3://projet-budget-famille/data/workflow_runs/2026-06-29/codif-vvkv9/decide-coicop/predictions.parquet</code> (voir <a href="../modelisation/index.html">résultats bruts</a> — qui peuvent refléter un run plus récent si <code>CHEMIN_S3_MODELISATION</code> a changé depuis).</p>
<section id="analyse-des-erreurs-de-la-baseline" class="level2">
<h2 class="anchored" data-anchor-id="analyse-des-erreurs-de-la-baseline">Analyse des erreurs de la baseline</h2>
</section>
<section id="performance-du-modèle" class="level2">
<h2 class="anchored" data-anchor-id="performance-du-modèle">Performance du modèle</h2>
<p><strong>Niveau de performance.</strong> Avec le seuil par défaut de 0.5 (on prédit “baseline correcte” dès que <code>P(baseline correcte) &gt; 0.5</code>), le modèle atteint 86.0 % d’accuracy sur le test (ROC AUC 0.946), contre 84.6 % ± 0.6 en validation croisée (AUC 0.935 ± 0.005). L’écart entre les deux est faible : le résultat n’est pas un coup de chance lié au découpage train/test.</p>
<p>L’accuracy globale masque cependant une asymétrie importante entre les deux classes : sur les erreurs réelles de la baseline (263 cas du test), le modèle en repère 87 % (rappel), mais avec une précision de seulement 64 % — environ un tiers de ce qu’il signale comme “fausse” est en réalité correct. Sur les baselines réellement correctes (902 cas), 86 % sont bien reconnues comme telles, mais 128 sont signalées à tort comme fausses.</p>
<p><strong>Features les plus importantes.</strong> <code>nb_accords_max</code> (taille du plus gros groupe d’accord entre classifieurs) domine largement (34.5 % de l’importance), suivi de <code>ttc_conf_1</code> (14.9 %) et <code>unanimite</code> (9.1 %) : sans surprise, le signal principal du modèle est le niveau de consensus entre les classifieurs de base. Les scores de confiance individuels (<code>rag_confidence</code>, <code>lcs_distance</code>…) et <code>budget</code> pèsent chacun autour de 5-6 %. <code>shop_type_name</code> et <code>source</code> sont les moins utiles (&lt; 2 % chacune).</p>
</section>
<section id="erreurs-manquées-par-le-modèle" class="level2">
<h2 class="anchored" data-anchor-id="erreurs-manquées-par-le-modèle">Erreurs manquées par le modèle</h2>
<p><strong>Le signal le plus trompeur : la confiance de TTC.</strong> La médiane de <code>ttc_conf_1</code> est nettement plus haute pour les erreurs manquées (0.99) que pour celles bien détectées (0.78) : dans les cas manqués, TTC (l’arbitre de la baseline) est confiant <em>à tort</em>, et cette confiance abusive contamine la probabilité prédite par la RF — cohérent avec le fait que <code>ttc_conf_1</code> soit la 2ᵉ feature la plus importante du modèle. <code>nb_accords_max</code> suit la même logique, dans une moindre mesure (médiane 2 vs 1.5) : même un accord entre deux classifieurs, quand il est fortuit, suffit à faire pencher le modèle vers “correcte” à tort. <code>rag_confidence</code>, <code>ragann_confidence</code> et <code>budget</code> ne distinguent en revanche pas les deux groupes.</p>
<p><strong>Par division COICOP</strong>, la division 01 (Alimentation, boissons) concentre 20 des 35 erreurs manquées (57 %), avec un taux de erreurs manquées parmi ses propres erreurs (20 %) supérieur à la moyenne globale (13.3 %). Cet effet reste cependant surtout un effet de volume : la division 01 représente déjà 38 % de toutes les erreurs de baseline du test. Aucune autre division ne se détache nettement, la plupart affichant des taux comparables ou nuls, souvent sur de faibles effectifs.</p>
<p><strong>Limite du modèle actuel.</strong> Ces cas manqués partagent un profil commun : un signal de confiance élevé (accord entre classifieurs et/ou confiance TTC) qui s’avère malgré tout faux. Le modèle actuel n’a pas accès à d’information capable de distinguer un consensus fiable d’un consensus biaisé — améliorer sa détection nécessiterait probablement une feature capturant <em>pourquoi</em> les classifieurs sont d’accord (ex. proximité lexicale du texte à coder avec des cas ambigus connus), plutôt qu’un simple comptage d’accords.</p>
</section>
<section id="réannotation-manuelle-de-35-cas-manqués-par-la-rf" class="level2">
<h2 class="anchored" data-anchor-id="réannotation-manuelle-de-35-cas-manqués-par-la-rf">Réannotation manuelle de 35 cas manqués par la RF</h2>
<p>35 cas manqués par la RF sur ce run ont été réannotés manuellement (par Mathis) pour distinguer une vraie erreur de la baseline d’un problème d’annotation ou de troncature :</p>
<ul>
<li><strong>Erreur réelle</strong> : la baseline a bien tort, confirmé par la relecture.</li>
<li><strong>Ambigu</strong> : la baseline a tort, mais la réponse reste litigieuse (presque acceptable).</li>
<li><strong>Problème de troncature</strong> : la baseline a raison, la comparaison brute au niveau 4 ne le détectait pas à cause d’un souci de troncature du code.</li>
<li><strong>Erreur d’annotation</strong> : la baseline a raison, mais le code du jeu de données (<code>code_vrai</code>) semble lui-même erroné.</li>
</ul>
<p><strong>Note de méthode.</strong> Ce tableau recolle les 35 lignes annotées aux cas “manqués” évalués par validation croisée à 5 folds sur l’ensemble du run (<code>entrainer_evaluer_cv</code>), pas au split 80/20 utilisé par la page <a href="../modelisation/index.html">Modélisation</a> : ce dernier ne couvre que 20 % du run, alors que les 35 lignes ont été choisies à l’origine sur l’ensemble du run — la plupart n’apparaîtraient donc jamais dans ce split réduit. Avec la validation croisée, <strong>24 des 35 lignes annotées</strong> retombent bien en cas manqué. Les 11 restantes s’expliquent entièrement : 5 sont les cas marqués “problème de troncature” par Mathis (la comparaison brute niveau 4 les montrait à tort comme des erreurs à l’époque ; le bug de troncature identifié a depuis été corrigé, ce ne sont donc plus des erreurs manquées aujourd’hui), et 6 sont désormais correctement détectées par le modèle (donc plus “manquées”).</p>
<p><strong>Répartition des 24 cas retrouvés :</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Catégorie</th>
<th>n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Erreur réelle</td>
<td>10</td>
</tr>
<tr class="even">
<td>Erreur d’annotation</td>
<td>9</td>
</tr>
<tr class="odd">
<td>Ambigu</td>
<td>5</td>
</tr>
<tr class="even">
<td>Problème de troncature</td>
<td>0</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Ligne</th>
<th>Code vrai</th>
<th>Code baseline</th>
<th>Code (Mathis)</th>
<th>Catégorie</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>143</td>
<td>09.3.2.2</td>
<td>01.1.3.1</td>
<td>09.3.2.2</td>
<td>Erreur réelle</td>
</tr>
<tr class="even">
<td>242</td>
<td>01.1.3</td>
<td>01.1.3.4</td>
<td>01.1.3</td>
<td>Erreur réelle</td>
</tr>
<tr class="odd">
<td>525</td>
<td>07.4.1</td>
<td>07.4.1.1</td>
<td>07.4.1</td>
<td>Ambigu</td>
</tr>
<tr class="even">
<td>566</td>
<td>01.1.1.3</td>
<td>01.1.7.9</td>
<td>01.1.7.9</td>
<td>Erreur d’annotation</td>
</tr>
<tr class="odd">
<td>592</td>
<td>01.1.3.3</td>
<td>01.1.3.4</td>
<td>01.1.3.4</td>
<td>Erreur d’annotation</td>
</tr>
<tr class="even">
<td>880</td>
<td>01.1.9.1</td>
<td>01.1.1.3</td>
<td>01.1.9.1</td>
<td>Erreur réelle</td>
</tr>
<tr class="odd">
<td>973</td>
<td>11.1.1</td>
<td>11.1.1.1</td>
<td>11.1.1</td>
<td>Erreur réelle</td>
</tr>
<tr class="even">
<td>1266</td>
<td>09.7.1</td>
<td>99.1</td>
<td>99.1</td>
<td>Erreur d’annotation</td>
</tr>
<tr class="odd">
<td>1836</td>
<td>98.4</td>
<td>01.1.9.1</td>
<td>98.1</td>
<td>Erreur réelle</td>
</tr>
<tr class="even">
<td>2262</td>
<td>04.3.1.1</td>
<td>05.6.1.1</td>
<td>04.3.1.1</td>
<td>Erreur réelle</td>
</tr>
<tr class="odd">
<td>2307</td>
<td>01.1.3.3</td>
<td>01.1.3.4</td>
<td>01.1.3.4</td>
<td>Erreur d’annotation</td>
</tr>
<tr class="even">
<td>2740</td>
<td>01.1.2.2</td>
<td>01.1.9.1</td>
<td>98.1</td>
<td>Erreur réelle</td>
</tr>
<tr class="odd">
<td>3086</td>
<td>09.2.2.2</td>
<td>09.2.2.1</td>
<td>09.2.2.2</td>
<td>Erreur réelle</td>
</tr>
<tr class="even">
<td>3147</td>
<td>01.1.7.5</td>
<td>01.1.7.9</td>
<td>01.1.7.9</td>
<td>Erreur d’annotation</td>
</tr>
<tr class="odd">
<td>3326</td>
<td>03.1.2</td>
<td>05.6.1.9</td>
<td>99.1</td>
<td>Erreur réelle</td>
</tr>
<tr class="even">
<td>3990</td>
<td>05.6.2.9</td>
<td>05.2.1.2</td>
<td>05.2.1.2</td>
<td>Erreur d’annotation</td>
</tr>
<tr class="odd">
<td>4565</td>
<td>05.3.2</td>
<td>05.3.2.9</td>
<td>05.3.2.9</td>
<td>Erreur d’annotation</td>
</tr>
<tr class="even">
<td>4718</td>
<td>01.1.2.2</td>
<td>01.1.2.5</td>
<td>98.1</td>
<td>Ambigu</td>
</tr>
<tr class="odd">
<td>4965</td>
<td>01</td>
<td>01.1.1.3</td>
<td>01</td>
<td>Erreur réelle</td>
</tr>
<tr class="even">
<td>5117</td>
<td>01.1.9.1</td>
<td>01.1.1.5</td>
<td>01.1.9.1</td>
<td>Ambigu</td>
</tr>
<tr class="odd">
<td>5336</td>
<td>01.1.2.3</td>
<td>01.1.2.2</td>
<td>01.1.2.3</td>
<td>Ambigu</td>
</tr>
<tr class="even">
<td>5360</td>
<td>01.1.3.1</td>
<td>01.1.3.3</td>
<td>01.1.3.3</td>
<td>Erreur d’annotation</td>
</tr>
<tr class="odd">
<td>5505</td>
<td>04.3.1.1</td>
<td>05.5.2.1</td>
<td>05.5.2.1</td>
<td>Erreur d’annotation</td>
</tr>
<tr class="even">
<td>5534</td>
<td>01.1.2.3</td>
<td>01.1.2.2</td>
<td>01.1.2.3</td>
<td>Ambigu</td>
</tr>
</tbody>
</table>
<p><strong>Sur les 15 vraies erreurs confirmées</strong> (Erreur réelle + Ambigu), ce que la baseline a suivi : le vote majoritaire dans 14 cas, TTC arbitrant une égalité dans le dernier (ligne 5117). Quand c’est la majorité, RAG-ANN en faisait partie dans 5 cas sur 14 (donc contribuait à l’erreur), et était le dissident (minoritaire, donc pas en cause) dans les 9 autres — échantillon trop restreint pour en tirer une conclusion générale, mais cohérent avec le diagnostic plus haut : RAG-ANN n’est pas plus souvent responsable des erreurs de la baseline que les autres classifieurs sur ce run (sa régression documentée plus bas n’apparaît que sur les runs suivants).</p>
</section>
<section id="compromis-précisionrappel" class="level2">
<h2 class="anchored" data-anchor-id="compromis-précisionrappel">Compromis précision/rappel</h2>
<p>Sur les 1165 observations du test, 263 (22.6 %) sont de vraies erreurs de baseline. C’est ce que ce compromis cherche à intercepter avant qu’elles ne passent inaperçues.</p>
<ul>
<li><strong>Seuil 0.99 / 0.95</strong> : détecte 100 % des erreurs, mais au prix d’envoyer 86 % / 71 % du volume au LLM — cela annule une grande partie de l’intérêt économique de la baseline.</li>
<li><strong>Seuil 0.90</strong> : ne manque qu’<strong>1 erreur sur 263</strong> (99.6 % détectées), en envoyant 61 % du volume au LLM (39 % d’appels évités par rapport à tout envoyer).</li>
<li><strong>Seuil 0.80</strong> : manque 6 erreurs (97.7 % détectées), pour 51 % du volume envoyé.</li>
<li><strong>Seuil 0.50 (par défaut de <code>.predict()</code>)</strong> : le plus économique (31 % du volume envoyé), mais laisse passer 35 erreurs non détectées (13 % des erreurs de baseline), et parmi ce qu’on garde sans LLM, 4.3 % sont en réalité fausses (précision sur “correcte” = 95.7 %).</li>
</ul>
</section>
<section id="modèle-de-re-ranking-sirus-diagnostic-de-la-baisse-daccuracy-sur-les-runs-suivants" class="level2">
<h2 class="anchored" data-anchor-id="modèle-de-re-ranking-sirus-diagnostic-de-la-baisse-daccuracy-sur-les-runs-suivants">Modèle de re-ranking SIRUS : diagnostic de la baisse d’accuracy sur les runs suivants</h2>
<p>Cf. <a href="../modelisation/sirus.html">SIRUS — synthèse finale</a> pour le modèle de re-ranking candidat-level entraîné sur le run courant (sélection du meilleur candidat parmi les 4 classifieurs de base). Cette section documente un diagnostic fait a posteriori sur ce run-ci (<code>codif-vvkv9</code>) : pourquoi l’accuracy de ce modèle chute sur les deux runs suivants (<code>codif-8m8jn</code> du 2026-07-23, <code>codif-x98xl</code> du 2026-07-30), et pourquoi ce n’est pas un problème de généralisation du modèle SIRUS lui-même.</p>
<p><strong>Comparaison de performance</strong> (modèle candidat-level, split 80/20 par produit, seed 42) :</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Modèle</th>
<th>Accuracy produit</th>
<th>Borne haute</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Entraîné et testé sur ce run (test 20 %)</td>
<td>96.7 %</td>
<td>98.1 %</td>
</tr>
<tr class="even">
<td>Entraîné sur ce run, testé sur <code>x98xl</code> (même split que réentraîné)</td>
<td>77.8 %</td>
<td>87.9 %</td>
</tr>
<tr class="odd">
<td>Réentraîné directement sur <code>x98xl</code> (test 20 %)</td>
<td>78.5 %</td>
<td>87.9 %</td>
</tr>
</tbody>
</table>
<p>(Pour référence, accuracy du modèle entraîné sur ce run, appliqué à l’intégralité de <code>x98xl</code> [5881 produits] : 77.7 %. Recalage de <code>code_candidat_n1</code> sur les catégories connues de ce modèle : 0 % de candidats concernés, 0 % de produits entièrement recalés — le recalage ne biaise donc pas cette comparaison.)</p>
<p><strong>Réentraîner n’aide quasiment pas</strong> (77.8 % vs 78.5 %, moins d’un point d’écart) : ce n’est donc pas un défaut de généralisation de SIRUS, mais une baisse de la <strong>borne haute</strong> elle-même (98.1 % ici, 87.9 % sur <code>x98xl</code>) — moins de bons candidats disponibles en amont, peu importe le modèle de choix utilisé derrière.</p>
<p><strong>Diagnostic : quel classifieur décroche ?</strong> Taux de correspondance entre le code proposé par chaque classifieur de base et le vrai code (niveau 4) :</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Classifieur</th>
<th>Ce run (2026-06-29)</th>
<th>2026-07-23 (<code>8m8jn</code>)</th>
<th>2026-07-30 (<code>x98xl</code>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>lcs_code</code></td>
<td>46.8 %</td>
<td>45.8 %</td>
<td>45.7 %</td>
</tr>
<tr class="even">
<td><code>rag_code</code></td>
<td>52.5 %</td>
<td>52.6 %</td>
<td>52.2 %</td>
</tr>
<tr class="odd">
<td><code>ragann_code</code></td>
<td><strong>97.0 %</strong></td>
<td><strong>70.8 %</strong></td>
<td><strong>70.3 %</strong></td>
</tr>
<tr class="even">
<td><code>ttc_code_1</code></td>
<td>74.3 %</td>
<td>74.1 %</td>
<td>74.2 %</td>
</tr>
</tbody>
</table>
<p><strong><code>ragann_code</code> (RAG-ANN) est le classifieur en cause</strong> : son taux de correspondance chute de 97.0 % à ~70 % sur les deux runs suivants, sans amélioration entre le 23 et le 30 juillet — régression toujours présente au 30 juillet. LCS, RAG et TTC restent stables. C’est cette régression qui explique la baisse de borne haute (et donc d’accuracy du re-ranking), pas un problème de modèle SIRUS ni de généralisation — la vraie correction est en amont (pipeline RAG-ANN), pas dans le re-ranking.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/MathisKacer\.github\.io\/codification_auto_coicop\.git\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Rapport de stage — codification automatique COICOP</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>