<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-08-21">

<title>Le top-3 de TTC – Codification automatique COICOP</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-505cb934e192d125575319552c8b77a8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Codification automatique COICOP</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Accueil</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../stats-descriptives/index.html" aria-current="page"> 
<span class="menu-text">Fiabilité des classifieurs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../modelisation/index.html"> 
<span class="menu-text">Modélisation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../interpretation/index.html"> 
<span class="menu-text">Interprétation</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../stats-descriptives/ttc-top3.html">Le top-3 de TTC</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../stats-descriptives/apercu-donnees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Aperçu des données</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../stats-descriptives/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fiabilité des classifieurs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../stats-descriptives/accords-unanimes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Accords unanimes des 4 classifieurs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../stats-descriptives/trois-contre-un.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3 classifieurs contre 1 dissident</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../stats-descriptives/seul-correct.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Un seul classifieur a raison</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../stats-descriptives/ttc-top3.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Le top-3 de TTC</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../stats-descriptives/profondeur-codes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Profondeur et qualité des codes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../stats-descriptives/calibration-confiance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calibration des scores de confiance</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../stats-descriptives/accuracy-prix-collecte.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Accuracy par prix et mode de collecte</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#justesse-de-chaque-rang-ttc" id="toc-justesse-de-chaque-rang-ttc" class="nav-link active" data-scroll-target="#justesse-de-chaque-rang-ttc">Justesse de chaque rang TTC</a></li>
  <li><a href="#valeur-ajoutée-des-rangs-2-et-3" id="toc-valeur-ajoutée-des-rangs-2-et-3" class="nav-link" data-scroll-target="#valeur-ajoutée-des-rangs-2-et-3">Valeur ajoutée des rangs 2 et 3</a></li>
  <li><a href="#ttc-a-t-il-raison-seul" id="toc-ttc-a-t-il-raison-seul" class="nav-link" data-scroll-target="#ttc-a-t-il-raison-seul">TTC a-t-il raison seul ?</a></li>
  <li><a href="#pour-la-modélisation" id="toc-pour-la-modélisation" class="nav-link" data-scroll-target="#pour-la-modélisation">Pour la modélisation</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Le top-3 de TTC</h1>
<p class="subtitle lead">Justesse des rangs 2 et 3, valeur ajoutée du top-3, et cas où TTC a raison seul</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 21, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>TTC (TorchTextClassifier) ne fournit pas un seul code mais un <strong>classement de ses trois meilleures propositions</strong> (<code>ttc_code_1</code>, <code>ttc_code_2</code>, <code>ttc_code_3</code>), chacune avec une confiance. Les autres analyses du site n’utilisent que le rang 1 ; cette page regarde ce qu’apportent les rangs 2 et 3, et isole les cas où TTC est le seul à trouver le bon code. Toutes les comparaisons sont faites au <strong>niveau 4</strong> (sous-classe).</p>
<section id="justesse-de-chaque-rang-ttc" class="level2">
<h2 class="anchored" data-anchor-id="justesse-de-chaque-rang-ttc">Justesse de chaque rang TTC</h2>
<p>Part des produits pour lesquels le code d’un rang donné correspond au vrai code. La dernière ligne — le vrai code présent <strong>quelque part</strong> dans le top-3 — est le plafond que l’on atteindrait en sachant toujours choisir le bon rang.</p>
<div id="cbf61abc" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Cas</th>
<th data-quarto-table-cell-role="th">Effectif</th>
<th data-quarto-table-cell-role="th">% des produits</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Rang 1 correct</td>
<td>4362</td>
<td>74.2%</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Rang 2 correct</td>
<td>422</td>
<td>7.2%</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Rang 3 correct</td>
<td>155</td>
<td>2.6%</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Vrai code présent dans le top-3</td>
<td>4939</td>
<td>84.0%</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="9ee0116d" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display cell-output-markdown">
<p>Le rang 1 seul est correct dans <strong>74.2%</strong> des cas, mais le vrai code figure dans le top-3 dans <strong>84.0%</strong> des cas — soit <strong>9.8 points</strong> de couverture supplémentaire dormant dans les rangs 2 et 3. (TTC fournit toujours un rang 2 et un rang 3 : présents dans 100.0% et 100.0% des cas.)</p>
</div>
</div>
</section>
<section id="valeur-ajoutée-des-rangs-2-et-3" class="level2">
<h2 class="anchored" data-anchor-id="valeur-ajoutée-des-rangs-2-et-3">Valeur ajoutée des rangs 2 et 3</h2>
<p>La question opérationnelle : quand le rang 1 se trompe, à quelle fréquence le vrai code est-il quand même récupérable en rang 2 ou 3 ?</p>
<div id="260ff2a5" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Cas (parmi les produits où le rang 1 a tort)</th>
<th data-quarto-table-cell-role="th">Effectif</th>
<th data-quarto-table-cell-role="th">% des cas où rang 1 a tort</th>
<th data-quarto-table-cell-role="th">% de tous les produits</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Rang 2 rattrape</td>
<td>422</td>
<td>27.8%</td>
<td>7.2%</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Rang 3 rattrape</td>
<td>155</td>
<td>10.2%</td>
<td>2.6%</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Rang 2 ou 3 rattrape</td>
<td>577</td>
<td>38.0%</td>
<td>9.8%</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="742143ff" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display cell-output-markdown">
<p>Sur les <strong>1519</strong> produits où le rang 1 de TTC se trompe, le vrai code est malgré tout présent en rang 2 ou 3 dans <strong>577</strong> cas (<strong>38.0%</strong>). C’est le gain potentiel qu’on récupérerait en exploitant le top-3 plutôt que le seul rang 1.</p>
</div>
</div>
<p><strong>La confiance discrimine-t-elle les rangs 2/3 corrects ?</strong> Si oui, <code>ttc_conf_2</code> et <code>ttc_conf_3</code> sont des variables utiles pour départager. Confiance médiane selon que le rang est correct ou non :</p>
<div id="4c169062" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Rang</th>
<th data-quarto-table-cell-role="th">Conf. médiane si correct</th>
<th data-quarto-table-cell-role="th">Conf. médiane si incorrect</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Rang 2</td>
<td>0.16</td>
<td>0.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Rang 3</td>
<td>0.04</td>
<td>0.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="ttc-a-t-il-raison-seul" class="level2">
<h2 class="anchored" data-anchor-id="ttc-a-t-il-raison-seul">TTC a-t-il raison seul ?</h2>
<p>Cas où TTC trouve le bon code alors qu’<strong>aucun</strong> des trois autres classifieurs de base (LCS, RAG, RAG-ANN) ne l’a — la contribution propre de TTC, qu’on perdrait en le retirant.</p>
<div id="c24d4b94" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Cas</th>
<th data-quarto-table-cell-role="th">Effectif</th>
<th data-quarto-table-cell-role="th">% des produits</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Rang 1 correct, aucun autre classifieur correct</td>
<td>510</td>
<td>8.7%</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Vrai code dans le top-3, aucun autre classifieur correct</td>
<td>691</td>
<td>11.7%</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="9027b26f" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display cell-output-markdown">
<p>TTC est seul à trouver le bon code (rang 1) dans <strong>510</strong> cas (<strong>8.7%</strong>). En comptant son top-3, il apporte le vrai code qu’aucun autre classifieur n’a proposé dans <strong>691</strong> cas (<strong>11.7%</strong>).</p>
</div>
</div>
<p><strong>Détail des cas où TTC (rang 1) est seul correct</strong>, avec la division COICOP (niveau 1) du vrai code. Seuls la ligne et les codes sont exposés (pas le libellé brut du produit).</p>
<div id="a53c252e" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div style="max-height:400px;overflow-y:auto;border:1px solid #ddd;border-radius:6px;">
<table class="dataframe table table-sm table-striped caption-top small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Ligne</th>
<th data-quarto-table-cell-role="th">Code vrai</th>
<th data-quarto-table-cell-role="th">Division</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>15</td>
<td>01.1.8.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>18</td>
<td>05.3.3</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>21</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>37</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>94</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>101</td>
<td>01.1.8.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>115</td>
<td>13.2.9.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>118</td>
<td>99.2</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="odd">
<td>121</td>
<td>01.1.2.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>125</td>
<td>98.4</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="odd">
<td>135</td>
<td>01.1.2.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>147</td>
<td>01.1.9.4</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>191</td>
<td>11.1.1.2</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="even">
<td>197</td>
<td>01.1.4.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>227</td>
<td>09.7.4</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>234</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>237</td>
<td>05.4.0.3</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>252</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>265</td>
<td>98.1.4</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>307</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>311</td>
<td>01.1.1.4</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>318</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>320</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>321</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>344</td>
<td>07.3.1.1</td>
<td>Transports (07)</td>
</tr>
<tr class="even">
<td>353</td>
<td>09.4.7</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>362</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>371</td>
<td>01.1.2.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>375</td>
<td>01.2.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>407</td>
<td>01.1.4.7</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>414</td>
<td>01.2.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>440</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>445</td>
<td>01.1.6.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>447</td>
<td>01.1.1.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>452</td>
<td>01.1.8.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>514</td>
<td>05.5.3</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>516</td>
<td>02.1.3</td>
<td>Boissons alcoolisées, tabac et stupéfiants (02)</td>
</tr>
<tr class="even">
<td>519</td>
<td>09.4.6.1</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>533</td>
<td>11.1.1.1</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="even">
<td>538</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="odd">
<td>543</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>552</td>
<td>01.2.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>566</td>
<td>05.5.2.2</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>574</td>
<td>01.1.3.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>576</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>584</td>
<td>01.1.3.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>586</td>
<td>11.1.1.1</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="even">
<td>596</td>
<td>09.8</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>600</td>
<td>01.1.8.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>604</td>
<td>01.1.8.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>616</td>
<td>07.4.1.2</td>
<td>Transports (07)</td>
</tr>
<tr class="even">
<td>625</td>
<td>05.5.2.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>629</td>
<td>98.1.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>647</td>
<td>01.1.4.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>648</td>
<td>99.2</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="even">
<td>670</td>
<td>99.2</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="odd">
<td>684</td>
<td>01.1.4.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>691</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>696</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>712</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>770</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>785</td>
<td>01.1.2.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>787</td>
<td>01.1.8.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>794</td>
<td>01.1.2.2</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>796</td>
<td>01.1.6.8</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>802</td>
<td>98.1.3</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="odd">
<td>810</td>
<td>01.1.8.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>816</td>
<td>07.2.1.2</td>
<td>Transports (07)</td>
</tr>
<tr class="odd">
<td>825</td>
<td>01.2.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>827</td>
<td>98.1.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="odd">
<td>845</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>849</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>850</td>
<td>01.1.4.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>854</td>
<td>05.2.1.2</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>856</td>
<td>01.1.4.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>867</td>
<td>98.1.4</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="odd">
<td>880</td>
<td>99.2</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="even">
<td>882</td>
<td>11.1.1.2</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="odd">
<td>917</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>918</td>
<td>01.1.4.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>923</td>
<td>01.1.2.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>930</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>934</td>
<td>98.4</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>948</td>
<td>99.4</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="odd">
<td>955</td>
<td>02.1.3</td>
<td>Boissons alcoolisées, tabac et stupéfiants (02)</td>
</tr>
<tr class="even">
<td>962</td>
<td>01.2.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>970</td>
<td>01.1.4.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>996</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="odd">
<td>998</td>
<td>01.1.7.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1059</td>
<td>01.1.7.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1065</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1066</td>
<td>01.1.8.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1071</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>1076</td>
<td>01.1.8.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1082</td>
<td>01.1.4.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1083</td>
<td>01.1.4.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1091</td>
<td>01.1.4.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1095</td>
<td>09.7.4</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>1131</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1132</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1134</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1144</td>
<td>01.1.2.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1155</td>
<td>01.2.2</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1161</td>
<td>09.2.2.1</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>1166</td>
<td>01.1.7.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1167</td>
<td>09.7.1.9</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>1179</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>1182</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1184</td>
<td>01.1.4.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1188</td>
<td>01.1.4.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1214</td>
<td>01.1.4.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1225</td>
<td>05.5.2.2</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>1237</td>
<td>01.1.9.2</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1256</td>
<td>99.2</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="odd">
<td>1307</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1341</td>
<td>11.1.1.1</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="odd">
<td>1345</td>
<td>01.1.4.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1349</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1364</td>
<td>07.2.4.4</td>
<td>Transports (07)</td>
</tr>
<tr class="even">
<td>1372</td>
<td>01.2.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1396</td>
<td>98.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>1399</td>
<td>11.1.1.1</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="odd">
<td>1415</td>
<td>09.4.6.1</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>1426</td>
<td>01.1.2.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1447</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>1454</td>
<td>99.2</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="odd">
<td>1462</td>
<td>05.6.1.9</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>1470</td>
<td>98.4</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="odd">
<td>1479</td>
<td>98.1.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>1491</td>
<td>01.1.1.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1513</td>
<td>98.1.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>1537</td>
<td>02.1.1</td>
<td>Boissons alcoolisées, tabac et stupéfiants (02)</td>
</tr>
<tr class="odd">
<td>1542</td>
<td>01.1.4.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1551</td>
<td>01.1.4.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1574</td>
<td>98.1.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>1614</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1625</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>1635</td>
<td>01.1.3.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1651</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1655</td>
<td>07.2.3</td>
<td>Transports (07)</td>
</tr>
<tr class="odd">
<td>1661</td>
<td>09.3.2.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>1682</td>
<td>01.1.5.2</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1683</td>
<td>11.1.1.2</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="even">
<td>1706</td>
<td>11.1.1.2</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="odd">
<td>1710</td>
<td>01.2.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1723</td>
<td>99.1</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="odd">
<td>1732</td>
<td>09.3.2.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>1746</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1747</td>
<td>13.1.3.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>1760</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1765</td>
<td>01.1.3.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1779</td>
<td>01.1.2.2</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1791</td>
<td>01.1.2.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1810</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1816</td>
<td>01.1.8.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1844</td>
<td>11.1.1.2</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="odd">
<td>1853</td>
<td>98.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>1855</td>
<td>01.1.4.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1859</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1873</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1880</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1903</td>
<td>01.1.6.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1905</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1910</td>
<td>05.1.1.4</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>1922</td>
<td>05.5.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>1933</td>
<td>05.5.2.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>1946</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1956</td>
<td>03.1.2.3</td>
<td>Articles d'habillement et chaussures (03)</td>
</tr>
<tr class="odd">
<td>1966</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>1982</td>
<td>09.5.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>1986</td>
<td>01.2.2</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>1989</td>
<td>01.1.3.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>1995</td>
<td>09.2.2.1</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>2006</td>
<td>03.1.2.2</td>
<td>Articles d'habillement et chaussures (03)</td>
</tr>
<tr class="odd">
<td>2009</td>
<td>01.1.2.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2015</td>
<td>11.2.0.3</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="odd">
<td>2029</td>
<td>01.1.3.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2046</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2049</td>
<td>98.1.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>2051</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>2073</td>
<td>05.1.1.4</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>2074</td>
<td>11.1.1.2</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="odd">
<td>2078</td>
<td>01.1.8.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2083</td>
<td>07.2.4.4</td>
<td>Transports (07)</td>
</tr>
<tr class="odd">
<td>2113</td>
<td>01.1.7.4</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2118</td>
<td>01.1.3.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2135</td>
<td>07.4.1.2</td>
<td>Transports (07)</td>
</tr>
<tr class="even">
<td>2136</td>
<td>07.2.2.1</td>
<td>Transports (07)</td>
</tr>
<tr class="odd">
<td>2184</td>
<td>05.6.1.9</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>2203</td>
<td>10.5.0.1</td>
<td>Services de l'enseignement (10)</td>
</tr>
<tr class="odd">
<td>2227</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2234</td>
<td>01.1.2.2</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2262</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2268</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2284</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2291</td>
<td>01.1.4.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2292</td>
<td>01.1.8.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2311</td>
<td>01.1.1.4</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2322</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>2330</td>
<td>01.2.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2342</td>
<td>04.3.2</td>
<td>Logement, eau, gaz, électricité et autres combustibles (04)</td>
</tr>
<tr class="even">
<td>2343</td>
<td>02.1.2.1</td>
<td>Boissons alcoolisées, tabac et stupéfiants (02)</td>
</tr>
<tr class="odd">
<td>2349</td>
<td>09.2.1.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>2374</td>
<td>11.1.1.1</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="odd">
<td>2390</td>
<td>01.1.4.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2401</td>
<td>01.1.8.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2415</td>
<td>09.4.6.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>2423</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="odd">
<td>2455</td>
<td>13.1.3.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>2456</td>
<td>01.1.8.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2482</td>
<td>98.1.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>2488</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2503</td>
<td>03.1.2.2</td>
<td>Articles d'habillement et chaussures (03)</td>
</tr>
<tr class="even">
<td>2509</td>
<td>98.1.4</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="odd">
<td>2516</td>
<td>09.4.6.1</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>2531</td>
<td>01.1.8.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2543</td>
<td>01.1.4.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2579</td>
<td>01.1.5.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2599</td>
<td>11.1.1.2</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="even">
<td>2603</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2606</td>
<td>01.1.1.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2623</td>
<td>01.1.8.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2688</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2723</td>
<td>11.1.1.1</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="odd">
<td>2741</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2742</td>
<td>98.4</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="odd">
<td>2749</td>
<td>01.2.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2752</td>
<td>05.6.1.9</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>2763</td>
<td>11.1.1.1</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="even">
<td>2773</td>
<td>01.1.7.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2781</td>
<td>12.1.9</td>
<td>Assurance et services financiers (12)</td>
</tr>
<tr class="even">
<td>2789</td>
<td>02.1.1</td>
<td>Boissons alcoolisées, tabac et stupéfiants (02)</td>
</tr>
<tr class="odd">
<td>2800</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2815</td>
<td>09.2.2.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>2819</td>
<td>01.1.2.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2821</td>
<td>01.1.7.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2845</td>
<td>01.1.7.4</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2858</td>
<td>01.2.2</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2871</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2878</td>
<td>08.1.3.2</td>
<td>Information et communication (08)</td>
</tr>
<tr class="odd">
<td>2888</td>
<td>11.1.1.2</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="even">
<td>2944</td>
<td>05.6.1.9</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>2958</td>
<td>09.6.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>2964</td>
<td>01.2.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2969</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>2991</td>
<td>01.1.9.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>2994</td>
<td>03.1.2.1</td>
<td>Articles d'habillement et chaussures (03)</td>
</tr>
<tr class="even">
<td>3001</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3042</td>
<td>99.2</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="even">
<td>3047</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>3059</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>3071</td>
<td>01.1.7.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3078</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>3080</td>
<td>99.1</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="odd">
<td>3103</td>
<td>01.1.2.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>3124</td>
<td>99.2</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="odd">
<td>3162</td>
<td>01.1.7.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>3191</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3209</td>
<td>01.1.1.4</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>3218</td>
<td>01.1.8.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3220</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>3241</td>
<td>11.1.1.2</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="odd">
<td>3247</td>
<td>09.3.1.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>3251</td>
<td>01.2.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3260</td>
<td>98.1.4</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>3273</td>
<td>01.1.2.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3319</td>
<td>09.3.2.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>3326</td>
<td>11.1.2.9</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="odd">
<td>3327</td>
<td>09.3.1.1</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>3351</td>
<td>01.1.4.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3364</td>
<td>01.1.7.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>3367</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3411</td>
<td>11.1.1.2</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="even">
<td>3414</td>
<td>01.1.1.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3441</td>
<td>98.1.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>3444</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3469</td>
<td>99.2</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="even">
<td>3478</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>3481</td>
<td>02.1.3</td>
<td>Boissons alcoolisées, tabac et stupéfiants (02)</td>
</tr>
<tr class="even">
<td>3483</td>
<td>01.1.1.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3489</td>
<td>98.1.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>3530</td>
<td>01.1.2.2</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3557</td>
<td>11.1.1.1</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="even">
<td>3559</td>
<td>05.3.2.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>3566</td>
<td>07.2.3</td>
<td>Transports (07)</td>
</tr>
<tr class="even">
<td>3571</td>
<td>01.1.1.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3587</td>
<td>02.3.0.9</td>
<td>Boissons alcoolisées, tabac et stupéfiants (02)</td>
</tr>
<tr class="even">
<td>3643</td>
<td>04.3.1.1</td>
<td>Logement, eau, gaz, électricité et autres combustibles (04)</td>
</tr>
<tr class="odd">
<td>3648</td>
<td>09.3.2.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>3676</td>
<td>01.1.2.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3683</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>3687</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>3696</td>
<td>01.1.4.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>3713</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3731</td>
<td>09.2.1.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>3732</td>
<td>99.2</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="odd">
<td>3753</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>3757</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>3769</td>
<td>07.2.2.2</td>
<td>Transports (07)</td>
</tr>
<tr class="even">
<td>3781</td>
<td>01.1.4.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3789</td>
<td>01.1.2.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>3791</td>
<td>01.1.3.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3798</td>
<td>01.1.7.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>3801</td>
<td>01.1.2.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3803</td>
<td>01.1.8.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>3812</td>
<td>09.2.2.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>3817</td>
<td>98.4</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>3846</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3863</td>
<td>01.1.9.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>3866</td>
<td>09.6.3</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>3869</td>
<td>05.6.1.9</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>3889</td>
<td>01.1.2.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>3907</td>
<td>98.1.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>3929</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>3946</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>3950</td>
<td>05.6.1.9</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>3973</td>
<td>09.4.6.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>3985</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="odd">
<td>3988</td>
<td>01.1.4.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>3990</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>3999</td>
<td>01.1.8.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>4002</td>
<td>01.1.9.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4012</td>
<td>09.8</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>4021</td>
<td>01.1.2.2</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4039</td>
<td>11.1.1.1</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="even">
<td>4044</td>
<td>09.3.2.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>4049</td>
<td>02.1.3</td>
<td>Boissons alcoolisées, tabac et stupéfiants (02)</td>
</tr>
<tr class="even">
<td>4051</td>
<td>07.2.3</td>
<td>Transports (07)</td>
</tr>
<tr class="odd">
<td>4054</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>4077</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>4095</td>
<td>01.1.8.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>4129</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="odd">
<td>4136</td>
<td>04.3.2</td>
<td>Logement, eau, gaz, électricité et autres combustibles (04)</td>
</tr>
<tr class="even">
<td>4160</td>
<td>05.5.2.2</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>4170</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>4173</td>
<td>07.2.3</td>
<td>Transports (07)</td>
</tr>
<tr class="odd">
<td>4186</td>
<td>05.6.1.9</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>4188</td>
<td>01.1.4.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4191</td>
<td>01.1.6.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>4205</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="odd">
<td>4212</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>4238</td>
<td>98.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="odd">
<td>4240</td>
<td>01.1.1.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>4241</td>
<td>01.1.1.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4261</td>
<td>01.1.4.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>4265</td>
<td>99.1</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="odd">
<td>4302</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>4317</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>4323</td>
<td>01.1.8.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>4324</td>
<td>01.1.8.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4328</td>
<td>05.6.1.9</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>4330</td>
<td>01.1.1.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4335</td>
<td>05.6.1.9</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>4336</td>
<td>01.1.4.7</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4339</td>
<td>99.2</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="even">
<td>4345</td>
<td>01.1.1.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4360</td>
<td>09.3.2.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>4364</td>
<td>98.1.3</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="odd">
<td>4379</td>
<td>11.1.1.1</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="even">
<td>4397</td>
<td>98.4</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="odd">
<td>4411</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>4416</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4434</td>
<td>98.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>4448</td>
<td>11.1.2.9</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="odd">
<td>4460</td>
<td>01.1.2.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>4464</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="odd">
<td>4483</td>
<td>07.2.3</td>
<td>Transports (07)</td>
</tr>
<tr class="even">
<td>4493</td>
<td>09.1.1.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>4494</td>
<td>03.1.2.3</td>
<td>Articles d'habillement et chaussures (03)</td>
</tr>
<tr class="even">
<td>4512</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>4514</td>
<td>11.1.1.2</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="even">
<td>4516</td>
<td>09.7.2.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>4543</td>
<td>02.1.2.1</td>
<td>Boissons alcoolisées, tabac et stupéfiants (02)</td>
</tr>
<tr class="even">
<td>4548</td>
<td>01.1.6.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4556</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>4585</td>
<td>01.1.4.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4593</td>
<td>99.2</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="even">
<td>4595</td>
<td>05.4.0.3</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>4636</td>
<td>01.1.5.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>4645</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="odd">
<td>4647</td>
<td>99.4</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="even">
<td>4654</td>
<td>01.1.4.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4664</td>
<td>98.1.3</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>4672</td>
<td>01.1.7.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4685</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>4707</td>
<td>02.1.2.2</td>
<td>Boissons alcoolisées, tabac et stupéfiants (02)</td>
</tr>
<tr class="odd">
<td>4712</td>
<td>01.1.2.2</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>4713</td>
<td>01.1.4.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4727</td>
<td>01.1.7.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>4728</td>
<td>09.3.2.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>4740</td>
<td>05.1.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>4741</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4777</td>
<td>01.1.4.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>4778</td>
<td>01.1.2.2</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4785</td>
<td>01.1.1.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>4807</td>
<td>01.1.4.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4831</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>4834</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4853</td>
<td>01.1.2.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>4860</td>
<td>01.1.2.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4874</td>
<td>98.1.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>4880</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4884</td>
<td>05.6.1.9</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>4887</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>4900</td>
<td>09.4.6.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>4906</td>
<td>09.4.6.1</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>4910</td>
<td>09.3.2.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>4912</td>
<td>01.1.7.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4926</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>4974</td>
<td>01.1.8.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>4976</td>
<td>12.1.9</td>
<td>Assurance et services financiers (12)</td>
</tr>
<tr class="even">
<td>5003</td>
<td>09.4.5</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>5004</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5005</td>
<td>98.4</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="odd">
<td>5012</td>
<td>98.4</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>5026</td>
<td>11.1.1.2</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="odd">
<td>5030</td>
<td>13.2.9.1</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>5038</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5039</td>
<td>08.3.2</td>
<td>Information et communication (08)</td>
</tr>
<tr class="even">
<td>5058</td>
<td>98.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="odd">
<td>5060</td>
<td>01.1.1.2</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5077</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5110</td>
<td>09.4.6.1</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>5111</td>
<td>11.1.1.1</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="odd">
<td>5117</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5119</td>
<td>01.1.4.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5127</td>
<td>01.1.2.2</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5134</td>
<td>05.6.1.9</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>5136</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5156</td>
<td>01.1.1.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5163</td>
<td>99.2</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="even">
<td>5167</td>
<td>98.4</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="odd">
<td>5171</td>
<td>09.7.1.9</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>5178</td>
<td>98.1.4</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="odd">
<td>5191</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>5207</td>
<td>99.2</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="odd">
<td>5215</td>
<td>98.1.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>5219</td>
<td>04.3.1.1</td>
<td>Logement, eau, gaz, électricité et autres combustibles (04)</td>
</tr>
<tr class="odd">
<td>5220</td>
<td>09.4.6.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>5225</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5231</td>
<td>09.4.6.1</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>5245</td>
<td>09.7.2.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>5246</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5254</td>
<td>09.3.2.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>5272</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>5287</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5288</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>5289</td>
<td>09.4.6.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>5315</td>
<td>01.1.2.2</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5317</td>
<td>01.1.2.2</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5329</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>5339</td>
<td>99.4</td>
<td>Hors COICOP (dons, impôts, opérations bancaires...) (99)</td>
</tr>
<tr class="odd">
<td>5367</td>
<td>01.1.1.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5402</td>
<td>05.3.2.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>5403</td>
<td>13.9.0.9</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="even">
<td>5404</td>
<td>09.3.2.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>5405</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>5428</td>
<td>01.1.8.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5430</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5458</td>
<td>98.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="odd">
<td>5465</td>
<td>08.1.3.2</td>
<td>Information et communication (08)</td>
</tr>
<tr class="even">
<td>5469</td>
<td>09.4.6.1</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>5471</td>
<td>98.4</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>5473</td>
<td>01.1.4.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5476</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5502</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>5508</td>
<td>09.7.4</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>5518</td>
<td>01.1.7.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5523</td>
<td>98.1.2</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="even">
<td>5524</td>
<td>13.1.2</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="odd">
<td>5533</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>5535</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="odd">
<td>5542</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>5557</td>
<td>11.1.1.2</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="odd">
<td>5560</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>5563</td>
<td>09.6.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="odd">
<td>5577</td>
<td>05.6.1.9</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>5585</td>
<td>01.1.2.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5586</td>
<td>01.1.4.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5589</td>
<td>98.4</td>
<td>Produit indéterminé/illisible (98)</td>
</tr>
<tr class="odd">
<td>5590</td>
<td>01.1.6.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5630</td>
<td>01.1.8.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5634</td>
<td>09.7.2.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>5637</td>
<td>13.1.1.1</td>
<td>Soins corporels, protection sociale et biens et services divers (13)</td>
</tr>
<tr class="odd">
<td>5640</td>
<td>06.2.3.1</td>
<td>Santé (06)</td>
</tr>
<tr class="even">
<td>5670</td>
<td>01.1.2.2</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5672</td>
<td>01.1.8.2</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5682</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5689</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5696</td>
<td>01.1.8.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5697</td>
<td>02.1.2.1</td>
<td>Boissons alcoolisées, tabac et stupéfiants (02)</td>
</tr>
<tr class="even">
<td>5703</td>
<td>01.1.4.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5708</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5713</td>
<td>01.1.7.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5716</td>
<td>11.2.0.3</td>
<td>Services de restauration et d'hébergement (11)</td>
</tr>
<tr class="even">
<td>5718</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5723</td>
<td>01.1.7.9</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5746</td>
<td>01.1.4.7</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5751</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5759</td>
<td>01.1.8.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5765</td>
<td>01.1.4.6</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5789</td>
<td>01.1.8.5</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5797</td>
<td>01.1.1.3</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5801</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5803</td>
<td>09.3.2.2</td>
<td>Loisirs, sport et culture (09)</td>
</tr>
<tr class="even">
<td>5810</td>
<td>01.1.3.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="odd">
<td>5832</td>
<td>05.6.1.1</td>
<td>Meubles, articles de ménage et entretien courant du foyer (05)</td>
</tr>
<tr class="even">
<td>5853</td>
<td>03.1.2.1</td>
<td>Articles d'habillement et chaussures (03)</td>
</tr>
<tr class="odd">
<td>5866</td>
<td>01.1.9.1</td>
<td>Produits alimentaires et boissons non alcoolisées (01)</td>
</tr>
<tr class="even">
<td>5877</td>
<td>04.3.1.1</td>
<td>Logement, eau, gaz, électricité et autres combustibles (04)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="pour-la-modélisation" class="level2">
<h2 class="anchored" data-anchor-id="pour-la-modélisation">Pour la modélisation</h2>
<p>Ces chiffres motivent directement l’ajout de features dérivées du top-3 de TTC (cf.&nbsp;<a href="../modelisation/index.html">modélisation</a> et la <a href="../modelisation/sirus.html">synthèse SIRUS</a>) : le rang auquel un code candidat apparaît chez TTC (<code>ttc_rang</code>) et la confiance associée portent un signal réel, puisque le vrai code est présent dans le top-3 bien plus souvent qu’en rang 1 seul, et que la confiance des rangs 2/3 sépare les bons des mauvais.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/MathisKacer\.github\.io\/codification_auto_coicop\.git\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Rapport de stage — codification automatique COICOP</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>