<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-08-21">

<title>SIRUS — synthèse finale – Codification automatique COICOP</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-505cb934e192d125575319552c8b77a8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Codification automatique COICOP</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Accueil</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../stats-descriptives/index.html"> 
<span class="menu-text">Fiabilité des classifieurs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../modelisation/index.html" aria-current="page"> 
<span class="menu-text">Modélisation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../interpretation/index.html"> 
<span class="menu-text">Interprétation</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../modelisation/sirus.html">SIRUS — synthèse finale</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../modelisation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modélisation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../modelisation/sirus.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">SIRUS — synthèse finale</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../modelisation/comparaison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Baseline+RF vs SIRUS</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#pourquoi-sirus" id="toc-pourquoi-sirus" class="nav-link active" data-scroll-target="#pourquoi-sirus">1. Pourquoi SIRUS ?</a></li>
  <li><a href="#organisation-des-données-la-table-longue-candidat-level" id="toc-organisation-des-données-la-table-longue-candidat-level" class="nav-link" data-scroll-target="#organisation-des-données-la-table-longue-candidat-level">2. Organisation des données : la table longue candidat-level</a></li>
  <li><a href="#modèle-principal" id="toc-modèle-principal" class="nav-link" data-scroll-target="#modèle-principal">3. Modèle principal</a></li>
  <li><a href="#features-additionnelles-budget-shop_type_name-source" id="toc-features-additionnelles-budget-shop_type_name-source" class="nav-link" data-scroll-target="#features-additionnelles-budget-shop_type_name-source">4. Features additionnelles : <code>budget</code>, <code>shop_type_name</code>, <code>source</code></a></li>
  <li><a href="#hyperparamètres-sirus" id="toc-hyperparamètres-sirus" class="nav-link" data-scroll-target="#hyperparamètres-sirus">5. Hyperparamètres SIRUS</a></li>
  <li><a href="#modèle-final" id="toc-modèle-final" class="nav-link" data-scroll-target="#modèle-final">6. Modèle final</a></li>
  <li><a href="#synthèse-et-recommandations" id="toc-synthèse-et-recommandations" class="nav-link" data-scroll-target="#synthèse-et-recommandations">7. Synthèse et recommandations</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">SIRUS — synthèse finale</h1>
<p class="subtitle lead">Pourquoi SIRUS, comment les données sont organisées, et tous les résultats obtenus sur le run courant (modèle, hyperparamètres), sans répétition</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 21, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<!--
Document de reference unique. Consolide dans l'ordre logique (pas
chronologique) tout ce qui a ete etabli sur SIRUS, a travers synthese.qmd,
synthese_bis.qmd, test.qmd, tentative_sirus.R et analyse_nouveau_run_x98xl.qmd :

1. Pourquoi SIRUS : ce qu'est le modele et pourquoi il convient a l'objectif
   de regles metier simples
2. Comment les donnees sont organisees (table longue candidat-level) pour
   alimenter ce modele
3. Le modele principal
4. Les features additionnelles (budget, shop_type_name, source)
5. Le reglage des hyperparametres SIRUS (num_regles, profondeur_max)
6. Le modele final retenu (cross-valide), avec ses regles completes

Ce document travaille sur un seul run a la fois (`objet_s3_courant`, en
tete du chunk de setup) -- a mettre a jour ici quand un nouveau run complet
(avec l'etape decide-coicop) est disponible. Le diagnostic historique de la
regression RAG-ANN (comparaison entre plusieurs runs, qui a motive ce choix
d'un seul run vivant ici) est documente une fois pour toutes, en dur, dans
[interpretation/2026-06-29.qmd](../interpretation/2026-06-29.qmd).

La gestion de la troncature des codes COICOP (retrait en cascade des "0"
terminaux, cf. `src/coicop.py::tronquer_niveau`) est appliquee partout
ci-dessous mais n'est pas re-detaillee sur ce site : elle a ete validee une
fois pour toutes en amont et n'est plus un point d'attention actif.

La section hyperparametres (`sirus.cv()`) est couteuse en temps de calcul
(~8 min) mais est recalculee a chaque rendu sur le run courant -- le cache
de freeze de Quarto evite de la relancer tant que ce document ne change
pas.
-->
<section id="pourquoi-sirus" class="level2">
<h2 class="anchored" data-anchor-id="pourquoi-sirus">1. Pourquoi SIRUS ?</h2>
<p>Le fil directeur de ce stage (cf.&nbsp;<a href="../index.html">Accueil</a> et <a href="../stats-descriptives/index.html">Fiabilité des classifieurs</a>) n’est pas seulement de prédire quand faire confiance aux classifieurs de base, mais d’en tirer des <strong>règles métier simples</strong> : des conditions du type “si tel classifieur tranche seul dans telle division, on le suit directement”, que quelqu’un du métier peut lire, valider et documenter, sans avoir besoin de comprendre un modèle de machine learning pour ça.</p>
<p>C’est précisément ce que ne permet pas la Random Forest utilisée dans <a href="../modelisation/index.html">Modélisation</a> pour détecter les erreurs de la baseline : elle prédit bien, mais reste une forêt de centaines d’arbres. Ses importances de features (section <a href="../modelisation/index.html#importances-des-features">Importances des features</a>) disent <em>quelle</em> variable compte, jamais <em>à partir de quel seuil</em> ni <em>en combinaison avec quoi</em> – impossible à relire comme une règle, encore moins à figer et documenter comme telle.</p>
<p><strong>SIRUS</strong> (<em>Stable and Interpretable RUle Set</em>, Bénard et al.) comble ce manque en gardant la logique d’une forêt aléatoire, mais avec une étape d’extraction en plus :</p>
<ol type="1">
<li>Il entraîne une forêt d’arbres CART, comme une Random Forest classique (rééchantillonnage, sous-ensemble de variables tirées à chaque nœud).</li>
<li>Il en extrait tous les chemins de décision (règles du type <code>si conf_ttc &lt; 0.78 et nb_votants &lt;= 1 alors ...</code>) jusqu’à une profondeur limitée (<code>max.depth</code>, 2 ici – des règles à 2 conditions maximum).</li>
<li>Il ne garde que les règles <strong>stables</strong> : celles qui reviennent souvent d’un arbre à l’autre, donc peu sensibles au tirage aléatoire précis de l’échantillon d’apprentissage – contrairement à une règle isolée d’un seul arbre, qui ne généraliserait pas. C’est cette garantie de stabilité (démontrée théoriquement par les auteurs) qui distingue SIRUS d’une extraction de règles “à la main” depuis une RF.</li>
<li>Il combine cette poignée de règles retenues (<code>num_regles</code>, 10 ici) par une régression linéaire simple sur leurs sorties, pour produire une probabilité calibrée.</li>
</ol>
<p>Le résultat concret (<code>sirus.print(modele)</code>, section 3) est directement une liste de conditions lisibles, chacune avec son poids – exactement le format d’une règle métier, pas une boîte noire. C’est pour ça que SIRUS est choisi ici plutôt qu’une RF classique ou qu’un réglage plus fin de celle-ci : l’enjeu n’est pas de gagner quelques points d’accuracy, mais d’obtenir un modèle dont la décision peut être <strong>relue, auditée et figée</strong> comme convention de codage, condition nécessaire pour qu’elle remplace un appel au LLM-judge en confiance.</p>
</section>
<section id="organisation-des-données-la-table-longue-candidat-level" class="level2">
<h2 class="anchored" data-anchor-id="organisation-des-données-la-table-longue-candidat-level">2. Organisation des données : la table longue candidat-level</h2>
<p>Le point de départ est un run du pipeline stocké sur le S3 (bucket <code>projet-budget-famille</code>), un fichier <code>predictions.parquet</code> par run, une ligne par produit (<code>ligne</code>) : pour chacun, le vrai code, et pour chacun des 4 classifieurs de base son code proposé plus un score (confiance ou distance selon le classifieur).</p>
<p>Ce format “large” (une colonne de code et une colonne de score <em>par classifieur</em>) n’est pas directement exploitable pour la question posée ici : on ne veut pas prédire “quel classifieur croire”, mais “ce candidat précis est-il le bon code”, une question générique qui doit pouvoir se poser pour n’importe lequel des candidats proposés, peu importe lequel des 4 classifieurs l’a proposé. Coder ça dans un format large obligerait à dupliquer la même logique 4 fois (une par classifieur), avec une notion de “confiance” différente à chaque fois.</p>
<p><strong>Solution retenue</strong> : un passage en format long, implémenté dans <code>construire_table_long()</code> (chargée dans le chunk de setup ci-dessus) – une ligne par <strong>candidat distinct</strong> proposé par au moins un des 4 classifieurs pour un produit donné (donc plusieurs lignes par produit s’ils proposent des codes différents, une seule s’ils sont tous d’accord). Chaque ligne agrège, pour ce candidat précis :</p>
<ul>
<li><strong>quels classifieurs ont voté pour lui</strong> (<code>vote_lcs/rag/ragann/ttc</code>, 0/1) et leur nombre (<code>nb_votants</code>) ;</li>
<li><strong>leur score de confiance associé</strong>, seulement pour les classifieurs qui ont effectivement voté pour ce candidat (cf.&nbsp;sentinelles ci-dessous) ;</li>
<li>la <strong>division du candidat</strong> (<code>code_candidat_n1</code>, troncature niveau 1) ;</li>
<li>si ce candidat est <strong>effectivement le bon code</strong> (<code>correcte</code>), la cible du modèle.</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>5881 produits (run courant) -&gt; 11836 lignes candidat-level (2.01 candidat distinct en moyenne par produit).</code></pre>
</div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 2%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 23%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">ligne</th>
<th style="text-align: left;">code_candidat</th>
<th style="text-align: left;">code_candidat_n1</th>
<th style="text-align: right;">vote_lcs</th>
<th style="text-align: right;">vote_rag</th>
<th style="text-align: right;">vote_ragann</th>
<th style="text-align: right;">vote_ttc</th>
<th style="text-align: right;">nb_votants</th>
<th style="text-align: right;">conf_rag</th>
<th style="text-align: right;">conf_ragann</th>
<th style="text-align: right;">conf_ttc</th>
<th style="text-align: right;">dist_lcs</th>
<th style="text-align: right;">correcte</th>
<th style="text-align: right;">budget</th>
<th style="text-align: left;">shop_type_name</th>
<th style="text-align: left;">source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">01.1.4.5</td>
<td style="text-align: left;">01</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">-1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.6842105</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.85</td>
<td style="text-align: left;">Magasins maxi-discompte</td>
<td style="text-align: left;">receipts_from_app</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">11.1.1.1</td>
<td style="text-align: left;">11</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">0.5882353</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">11.60</td>
<td style="text-align: left;">Restauration classique</td>
<td style="text-align: left;">manual_from_book</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: left;">09.2.1.1</td>
<td style="text-align: left;">09</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.0833333</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">338.00</td>
<td style="text-align: left;">Hypermarchés</td>
<td style="text-align: left;">manual_from_book</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: left;">09.7.4</td>
<td style="text-align: left;">09</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6.10</td>
<td style="text-align: left;">Grande surface spécialisée Loisir, Culture et TIC</td>
<td style="text-align: left;">manual_from_book</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: left;">01.1.4.5</td>
<td style="text-align: left;">01</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.3500000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.11</td>
<td style="text-align: left;">site de drive ou de grande surface alimentaire</td>
<td style="text-align: left;">receipts_from_app</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Ce choix a deux conséquences directement utiles pour la suite : le modèle n’a qu’une seule décision à apprendre (“ce candidat est-il le bon ?”), peu importe combien de candidats concurrents il y a ; et au moment de prédire, il suffit de garder, pour chaque produit, le candidat de plus haute probabilité (<code>slice_max</code>, section 3) pour obtenir une décision au niveau produit à partir de décisions au niveau candidat.</p>
<section id="sentinelles-de-confiance-quand-un-classifieur-na-pas-voté" class="level3">
<h3 class="anchored" data-anchor-id="sentinelles-de-confiance-quand-un-classifieur-na-pas-voté">Sentinelles de confiance quand un classifieur n’a pas voté</h3>
<p>Quand un classifieur ne vote pas pour un candidat donné, sa confiance est mise à une sentinelle hors de la plage réelle des valeurs (<code>-1</code> pour les confiances, bornées <code>[0, 1]</code> en pratique ; <code>1.5</code> pour <code>lcs_distance</code>, bornée <code>[0, 0.8]</code>) plutôt qu’à 0 ou <code>NA</code>. Vérifié non problématique pour un modèle à seuils comme SIRUS :</p>
<ul>
<li>Sentinelle toujours hors plage réelle (pas de collision avec une vraie valeur).</li>
<li>Redondant avec <code>vote_lcs/rag/ragann/ttc</code> (0/1) : aucune perte d’information, et permet à SIRUS de fusionner en une seule règle “vote faible OU absent” (ex. <code>if conf_ttc &lt; 0.78</code>), ce qui est le sens voulu.</li>
<li>Cas limite vérifié sur données réelles : 0 occurrence où un classifieur a voté (code non manquant) mais avec une confiance <code>NA</code> – le <code>coalesce()</code> de secours ne se déclenche jamais actuellement.</li>
</ul>
</section>
</section>
<section id="modèle-principal" class="level2">
<h2 class="anchored" data-anchor-id="modèle-principal">3. Modèle principal</h2>
<p>La table longue construite ci-dessus (<code>table_long</code>) sert directement de base d’entraînement. Split 80/20 par produit (pas par ligne candidat, pour ne pas répartir les candidats d’un même produit entre train et test), seed 42.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Proportion of class 1 = 0.442 - Sample size n = 9424"                            
 [2] "if nb_votants &lt; 2 then 0.146 (n=5297) else 0.822 (n=4127)"                       
 [3] "if conf_ttc &lt; 0.78 then 0.175 (n=5667) else 0.846 (n=3757)"                      
 [4] "if vote_ragann &lt; 1 then 0.164 (n=5223) else 0.789 (n=4201)"                      
 [5] "if conf_ragann &lt; 0.95 then 0.231 (n=6503) else 0.913 (n=2921)"                   
 [6] "if nb_votants &lt; 2 &amp; conf_ttc &lt; 0.78 then 0.0992 (n=4677) else 0.78 (n=4747)"     
 [7] "if vote_ragann &gt;= 1 &amp; conf_ttc &gt;= 0.78 then 0.955 (n=2713) else 0.235 (n=6711)"  
 [8] "if nb_votants &gt;= 2 &amp; conf_ragann &lt; 0.95 then 0.606 (n=1423) else 0.413 (n=8001)" 
 [9] "if conf_ragann &lt; 0.95 &amp; conf_ttc &lt; 0.78 then 0.106 (n=5014) else 0.825 (n=4410)" 
[10] "if vote_ttc &lt; 1 then 0.144 (n=4719) else 0.742 (n=4705)"                         
[11] "if conf_ragann &gt;= 0.7 &amp; conf_ttc &gt;= 0.78 then 0.957 (n=2689) else 0.237 (n=6735)"</code></pre>
</div>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Indicateur</th>
<th style="text-align: left;">Valeur</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Accuracy candidat-level</td>
<td style="text-align: left;">86.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Accuracy produit-level</td>
<td style="text-align: left;">78.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Borne haute</td>
<td style="text-align: left;">87.9%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Candidat-level vs produit-level</strong> : la première mesure juge chaque ligne de <code>test</code> indépendamment (<code>proba &gt; 0.5</code> correspond-elle à <code>correcte</code> ?), sans tenir compte du fait que plusieurs lignes peuvent concurrentiser pour le même produit. La seconde ne garde, par produit, que le candidat de plus haute probabilité (<code>slice_max</code>) et regarde si <em>celui-là</em> est le bon code – c’est la métrique qui compte réellement, puisqu’au final un seul code est retenu par produit. Les deux peuvent diverger : un modèle peut juger correctement chaque candidat pris isolément tout en choisissant, pour un produit donné, un mauvais candidat plutôt que le bon qui était pourtant proposé par un autre classifieur.</p>
<p>La borne haute borne toute amélioration possible du re-ranking : au-delà, il faudrait un meilleur candidat en amont (classifieurs de base), pas un meilleur modèle de choix.</p>
<section id="calibration-de-la-confiance" class="level3">
<h3 class="anchored" data-anchor-id="calibration-de-la-confiance">Calibration de la confiance</h3>
<div class="cell">
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">tranche</th>
<th style="text-align: right;">n</th>
<th style="text-align: left;">pct_correct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(0.2,0.3]</td>
<td style="text-align: right;">86</td>
<td style="text-align: left;">30.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">(0.3,0.4]</td>
<td style="text-align: right;">27</td>
<td style="text-align: left;">48.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(0.4,0.5]</td>
<td style="text-align: right;">211</td>
<td style="text-align: left;">51.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">(0.5,0.6]</td>
<td style="text-align: right;">195</td>
<td style="text-align: left;">73.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(0.6,0.7]</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">100.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">(0.7,0.8]</td>
<td style="text-align: right;">111</td>
<td style="text-align: left;">91.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(0.8,0.9]</td>
<td style="text-align: right;">544</td>
<td style="text-align: left;">97.4%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Deux zones nettes : une zone fiable (confiance élevée, &gt;98 % correct) et une zone incertaine (confiance faible, ~60-65 % correct) — un seuil simple sur <code>proba_gagnant</code> est directement exploitable comme critère d’escalade vers une reprise manuelle ou un LLM-judge.</p>
</section>
</section>
<section id="features-additionnelles-budget-shop_type_name-source" class="level2">
<h2 class="anchored" data-anchor-id="features-additionnelles-budget-shop_type_name-source">4. Features additionnelles : <code>budget</code>, <code>shop_type_name</code>, <code>source</code></h2>
<p>Même split train/test que le modèle principal. <code>budget</code> imputé par la médiane du train uniquement (pas de fuite) ; <code>shop_type_name</code> et <code>source</code> en facteurs dont les niveaux sont dérivés de <code>table_long</code> complet (avant split), pour éviter qu’une catégorie présente seulement dans le test (donc absente des niveaux du train) ne devienne un <code>NA</code> que <code>sirus.predict()</code> refuse.</p>
<div class="cell">
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Modele</th>
<th style="text-align: left;">Accuracy_produit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SIRUS (features de base)</td>
<td style="text-align: left;">78.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">SIRUS (+ budget/shop_type/source)</td>
<td style="text-align: left;">78.5%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Aucun gain</strong> sur le run courant, comme déjà observé sur le run ancien (où TTC et RAG-ANN sont pourtant proches en performance, hypothèse initiale que le contexte d’achat pourrait aider à arbitrer – infirmée aussi, cf. <a href="../interpretation/2026-06-29.html">interpretation/2026-06-29.qmd</a>) : aucune des règles retenues par SIRUS n’utilise ces 3 variables. Tout le signal utile est déjà dans les confiances des classifieurs eux-mêmes.</p>
<p><em>Limite de portée</em> : ce test est fait à <code>profondeur_max = 2</code> (règles à au plus 2 conditions), donc SIRUS a peu de marge pour combiner ces variables avec les autres. Un gain à plus grande profondeur n’est pas exclu par ce résultat – non prioritaire vu que le facteur limitant est ailleurs (cf. <a href="../interpretation/2026-06-29.html#modèle-de-re-ranking-sirus-diagnostic-de-la-baisse-daccuracy-sur-les-runs-suivants">diagnostic RAG-ANN</a>), mais à garder en tête si <code>profondeur_max</code> est un jour augmenté.</p>
</section>
<section id="hyperparamètres-sirus" class="level2">
<h2 class="anchored" data-anchor-id="hyperparamètres-sirus">5. Hyperparamètres SIRUS</h2>
<p><code>num_regles</code> (<code>num.rule</code>, défaut 10) et <code>profondeur_max</code> (<code>max.depth</code>, défaut/recommandé 2) sont paramétrables en tête de ce document pour tout retester en un seul endroit.</p>
<p><code>sirus.cv()</code> estime le nombre de règles optimal par validation croisée (nfold=10, ncv=10 – ~8 min de calcul), sur le train set du run courant (<code>train</code>, section 3). Deux valeurs de <code>p0</code> en ressortent : <code>p0.pred</code> (minimise l’erreur, recommandé en classification) et <code>p0.stab</code> (compromis avec la stabilité) – chacune correspondant à un nombre de règles différent.</p>
<div class="cell">
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Modele</th>
<th style="text-align: right;">Nb_regles</th>
<th style="text-align: left;">Accuracy_produit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">num.rule = 10 (actuel)</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">78.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">p0.pred cross-validé (20 règles)</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;">79.2%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Conclusion</strong> : le modèle cross-validé (20 règles) obtient 79.2% d’accuracy produit sur le run courant, contre 78.5% pour le réglage actuel (<code>num.rule =</code> 10) – un écart de +0.7 point. Si cet écart reste de l’ordre du dixième de point, il confirme que <code>num_regles</code> était déjà quasi-optimal et que le nombre de règles n’est pas un levier d’amélioration ; un écart net inviterait au contraire à aligner <code>num_regles</code> sur 20 en tête de document. Pour la même raison, augmenter <code>profondeur_max</code> au-delà de 2 (règles à 3 conditions plutôt que 2) n’a pas été testé ici – à envisager seulement si ce réglage s’avère un jour être le facteur limitant plutôt que la borne haute (cf. <a href="../interpretation/2026-06-29.html#modèle-de-re-ranking-sirus-diagnostic-de-la-baisse-daccuracy-sur-les-runs-suivants">diagnostic RAG-ANN</a>).</p>
</section>
<section id="modèle-final" class="level2">
<h2 class="anchored" data-anchor-id="modèle-final">6. Modèle final</h2>
<p>Le modèle retenu pour la suite (déjà entraîné à la section précédente, <code>modele_cv</code>) est donc celui cross-validé, avec 20 règles plutôt que les 10 par défaut – ses règles complètes, dans le même format que la section 3 :</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Proportion of class 1 = 0.442 - Sample size n = 9424"                            
 [2] "if nb_votants &lt; 2 then 0.146 (n=5297) else 0.822 (n=4127)"                       
 [3] "if conf_ttc &lt; 0.78 then 0.175 (n=5667) else 0.846 (n=3757)"                      
 [4] "if vote_ragann &lt; 1 then 0.164 (n=5223) else 0.789 (n=4201)"                      
 [5] "if conf_ragann &lt; 0.95 then 0.231 (n=6503) else 0.913 (n=2921)"                   
 [6] "if nb_votants &lt; 2 &amp; conf_ttc &gt;= 0.78 then 0.502 (n=620) else 0.438 (n=8804)"     
 [7] "if nb_votants &gt;= 2 &amp; conf_ragann &lt; 0.95 then 0.606 (n=1423) else 0.413 (n=8001)" 
 [8] "if conf_ragann &lt; 0.95 &amp; conf_ttc &lt; 0.78 then 0.106 (n=5014) else 0.825 (n=4410)" 
 [9] "if vote_ragann &gt;= 1 &amp; conf_ttc &gt;= 0.78 then 0.955 (n=2713) else 0.235 (n=6711)"  
[10] "if vote_ttc &lt; 1 then 0.144 (n=4719) else 0.742 (n=4705)"                         
[11] "if vote_ragann &gt;= 1 &amp; vote_ttc &gt;= 1 then 0.938 (n=2947) else 0.217 (n=6477)"     
[12] "if conf_ragann &gt;= 0.7 &amp; conf_ttc &gt;= 0.78 then 0.957 (n=2689) else 0.237 (n=6735)"
[13] "if vote_lcs &lt; 1 &amp; nb_votants &lt; 2 then 0.233 (n=3187) else 0.549 (n=6237)"        
[14] "if nb_votants &lt; 2 &amp; dist_lcs &lt; 1.5 then 0.0147 (n=2110) else 0.566 (n=7314)"     
[15] "if vote_ttc &lt; 1 &amp; conf_ragann &gt;= 0.95 then 0.673 (n=513) else 0.429 (n=8911)"    
[16] "if vote_ttc &lt; 1 &amp; nb_votants &gt;= 2 then 0.501 (n=617) else 0.438 (n=8807)"        
[17] "if vote_ragann &lt; 1 &amp; nb_votants &gt;= 2 then 0.518 (n=655) else 0.437 (n=8769)"     
[18] "if conf_ragann &lt; 0.7 then 0.167 (n=5320) else 0.799 (n=4104)"                    
[19] "if conf_rag &lt; 0.95 then 0.309 (n=6987) else 0.825 (n=2437)"                      
[20] "if nb_votants &gt;= 2 &amp; nb_votants &lt; 3 then 0.619 (n=1392) else 0.412 (n=8032)"     
[21] "if conf_rag &lt; 1 &amp; conf_ttc &lt; 0.78 then 0.156 (n=5405) else 0.827 (n=4019)"       </code></pre>
</div>
</div>
</section>
<section id="synthèse-et-recommandations" class="level2">
<h2 class="anchored" data-anchor-id="synthèse-et-recommandations">7. Synthèse et recommandations</h2>
<ul>
<li><strong>SIRUS livre bien l’objectif visé</strong> (section 1) : une poignée de règles seuils lisibles (<code>sirus.print(modele_cv)</code>, section 6 – modèle final), directement exploitables comme convention de codage, là où une Random Forest classique ne donnerait que des importances de features.</li>
<li><strong>Le nombre de règles est confirmé par cross-validation</strong> (section 5) : ni ce réglage, ni les features additionnelles (<code>budget</code>/<code>shop_type_name</code>/<code>source</code>, section 4) n’apportent de gain mesurable au-delà du réglage actuel.</li>
<li><strong>Le vrai facteur limitant est en amont</strong> : une régression du classifieur RAG-ANN, identifiée après le run du 2026-06-29 et toujours non corrigée à ce jour (cf. <a href="../interpretation/2026-06-29.html#modèle-de-re-ranking-sirus-diagnostic-de-la-baisse-daccuracy-sur-les-runs-suivants">diagnostic RAG-ANN</a>), plafonne la borne haute à 87.9% sur le run courant, contre 98.1 % sur le run du 2026-06-29. Aucun réglage de SIRUS ne peut compenser un candidat qui n’est simplement pas proposé.</li>
<li><strong>Prochaine étape recommandée</strong> : corriger RAG-ANN en amont plutôt que continuer à optimiser le re-ranking.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/MathisKacer\.github\.io\/codification_auto_coicop\.git\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Rapport de stage — codification automatique COICOP</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>